### ISSUE TITLE
about the formats of < ref_file >  < hyp_file >

### ISSUE THREAD

**Issue by genbei** [lvapeab/ter#1]
Hello, it's my first time to use this tool. What are the formats of these two files：< ref_file >  < hyp_file >
I want to calculate the ter values of two txt files, such as pe data and mt data of qe data. What should I do to use them?
Because I have encountered the following problems
`Warning, Invalid line: 随后 在 西南部 的   Appomattox   河 上 追赶 了   88   英里 。`
My script is`java -jar tercom.7.25.jar -r dev.pe -h dev.mt`

**Comment by lvapeab** [comment]
Hi,
this is a simple and dirty wrapper around the TER tool. You should include `tercom.7.25` in your path and run `ter.sh`. Something like: ` PATH=$PATH:. ter.sh -r  dev.pe  -t dev.mt`

However, I recommend you to take a look at https://github.com/lvapeab/coco-caption. Here's a more friendly wrapper to TER (you can use [evaluate_from_file.py](https://github.com/lvapeab/coco-caption/blob/master/evaluate_from_file.py)).

**Comment by genbei** [comment]
thank you very much!!!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvapeab/ter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 晚上9:17
收件人:&nbsp;"lvapeab/ter"<ter@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lvapeab/ter] about the formats of < ref_file &gt;  < hyp_file &gt; (#1)





 
Hi,
 this is a simple and dirty wrapper around the TER tool. You should include tercom.7.25 in your path and run ter.sh. Something like:  PATH=$PATH:. ter.sh -r  dev.pe  -t dev.mt
 
However, I recommend you to take a look at https://github.com/lvapeab/coco-caption. Here's a more friendly wrapper to TER.

**Comment by genbei** [comment]
Hello, I have some questions by running the code inside&nbsp;&nbsp;&nbsp;https://github.com/lvapeab/coco-caption

My script is&nbsp; python evaluate_from_file.py -t dev.mt -m ter -l zh -s 1 -r dev.peI want to calculate the ter value of each sentence in the text.There are a total of 1000 sentences, but the obvious values are not quite right, and the values are almost the same, as shown in the figure.



I am curious about how to use this tool conveniently, and whether I can input the output results into a txt text. I have not found the relevant parameters.
In addition, I used the BLEU value, and there are four BLEU values, which are quite different. I don't understand how these four BLEU values came from.
I'm sorry to bother you, because I really want to find out this tool and look forward to your reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvapeab/ter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 晚上9:17
收件人:&nbsp;"lvapeab/ter"<ter@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lvapeab/ter] about the formats of < ref_file &gt;  < hyp_file &gt; (#1)





 
Hi,
 this is a simple and dirty wrapper around the TER tool. You should include tercom.7.25 in your path and run ter.sh. Something like:  PATH=$PATH:. ter.sh -r  dev.pe  -t dev.mt
 
However, I recommend you to take a look at https://github.com/lvapeab/coco-caption. Here's a more friendly wrapper to TER.

**Comment by lvapeab** [comment]
Hi,

I cannot see the image you attach.

The `-s` option can be quite confusing. It shows the **accumulated** metrics of a corpus, on steps of that size. I needed this for a paper. If you want to compute the value of independent steps, I guess you can do something like:

```python3
indices = range(n - step_size, min(n, len(ref)))
```

in https://github.com/lvapeab/coco-caption/blob/38ee36e31dc88bb63a9e626da0d2c7ea8cd608e5/evaluate_from_file.py#L112. (I haven't tested it, so it may require some modifications). 

The results are printed to standard output, so you can redirect them to a file descriptor using `> file`.

BLEU computes a modified n-gram precision of hypotheses and references up to some order. The different values account for the max order considered. The canonical BLEU metric uses order 4, but lower ones may be useful in other scenarios. I recommend you to take a look at the paper: https://www.aclweb.org/anthology/P02-1040.pdf.

Let me know if you have more questions. I've opened the Issues section in the other repo, feel free to open an issue there.

**Comment by genbei** [comment]
You are right. I modified that line of code according to your opinion, and it seems that the TER value obtained may be correct, but there is still a big difference compared with the HTER value already given. The left side is the HTER value.
I'm not sure whether the score obtained this time is correct, because I want to use this score to construct pseudo QE data instead of artificial HTER value, and I want to ask you what you think
Ps doesn't know if you can see this picture.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvapeab/ter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午4:22
收件人:&nbsp;"lvapeab/ter"<ter@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lvapeab/ter] about the formats of < ref_file &gt;  < hyp_file &gt; (#1)





 
Hi,
 
I cannot see the image you attach.
 
The -s option can be quite confusing. It shows the accumulated metrics of a corpus, on steps of that size. I needed this for a paper. If you want to compute the value of independent steps, I guess you can do something like:
 indices = range(n - step_size, min(n, len(ref)))
 
in https://github.com/lvapeab/coco-caption/blob/38ee36e31dc88bb63a9e626da0d2c7ea8cd608e5/evaluate_from_file.py#L112. (I haven't tested it, so it may require some modifications).
 
The results are printed to standard output, so you can redirect them to a file descriptor using &gt; file.
 
BLEU computes a modified n-gram precision of hypotheses and references up to some order. The different values account for the max order considered. The canonical BLEU metric uses order 4, but lower ones may be useful in other scenarios. I recommend you to take a look at the paper: https://www.aclweb.org/anthology/P02-1040.pdf.
 
Let me know if you have more questions. I've opened the Issues section in the other repo, feel free to open an issue there.

**Comment by genbei** [comment]
> Hi,
> 
> I cannot see the image you attach.
> 
> The `-s` option can be quite confusing. It shows the **accumulated** metrics of a corpus, on steps of that size. I needed this for a paper. If you want to compute the value of independent steps, I guess you can do something like:
> 
> ```python
> indices = range(n - step_size, min(n, len(ref)))
> ```
> 
> in https://github.com/lvapeab/coco-caption/blob/38ee36e31dc88bb63a9e626da0d2c7ea8cd608e5/evaluate_from_file.py#L112. (I haven't tested it, so it may require some modifications).
> 
> The results are printed to standard output, so you can redirect them to a file descriptor using `> file`.
> 
> BLEU computes a modified n-gram precision of hypotheses and references up to some order. The different values account for the max order considered. The canonical BLEU metric uses order 4, but lower ones may be useful in other scenarios. I recommend you to take a look at the paper: https://www.aclweb.org/anthology/P02-1040.pdf.
> 
> Let me know if you have more questions. I've opened the Issues section in the other repo, feel free to open an issue there.

![ter](https://user-images.githubusercontent.com/57440758/101709371-4cba1380-3aca-11eb-9f52-174deed5ff2d.jpg)

**Comment by lvapeab** [comment]
Ok, now I'm seeing the picture. So, you have an MT file (`dev.mt`) and its post-edited version (`dev.pel`). You are given the HTER values for those sentences and that doesn't match with the values you are computing, right? Do you know how were these HTER values computed? The tokenization is the same in both cases? 

If you can share the first sentences I'll replicate your experiment

**Comment by genbei** [comment]
The calculation method of HTER is the TER algorithm used. The difference between them is that HTER corresponds to the manual post-editing translation and TER corresponds to the reference translation, (Therefore, when there is no manual post-editing translation, we use the reference translation to calculate TER instead of HTER value).
so I feel that there is a problem in the face of different calculated scores, I wonder if this code calls the tercom tool correctly，Or this code still has problems in calculating the TER value of sentences, but I can't contact the author either

My script is `python evaluate_from_file.py -t dev.mt -m ter -l zh -s 1 -r dev.pe > ter.txt`

I'll attach the document by the way

[dev.mt.txt](https://github.com/lvapeab/ter/files/5671417/dev.mt.txt)
[dev.pe.txt](https://github.com/lvapeab/ter/files/5671419/dev.pe.txt)
[dev.hter.txt](https://github.com/lvapeab/ter/files/5671420/dev.hter.txt)

**Comment by lvapeab** [comment]
Hi, 
sorry for the delayed response.

I just run (Python 3.7.9, Java openjdk 11.0.9.1) the script with the change I mentioned and it worked apparently well: 

`python evaluate_from_file.py --references data/dev.pe.txt --hypotheses data/dev.mt.txt  --step-size 1 --metrics ter`

Returns:


```
1 	Score:  {'TER': 0.6521739130434783}
2 	Score:  {'TER': 0.5142857142857142}
3 	Score:  {'TER': 0.6}
4 	Score:  {'TER': 0.625}
5 	Score:  {'TER': 0.7692307692307693}
6 	Score:  {'TER': 0.7333333333333333}
7 	Score:  {'TER': 0.5555555555555556}
8 	Score:  {'TER': 0.875}
9 	Score:  {'TER': 0.6}
10 	Score:  {'TER': 0.8333333333333334}
11 	Score:  {'TER': 0.45454545454545453}
12 	Score:  {'TER': 0.25}
13 	Score:  {'TER': 0.9230769230769231}
14 	Score:  {'TER': 0.5294117647058824}
```

That is consistent with the scores in `dev.hter.txt`.

**Comment by genbei** [comment]
when i run(python 3.6 openjdk 1.8.0_275)the script you given
But my score is different from yours    ：(
I'm very confused.

**Comment by genbei** [comment]
> Hi,
> sorry for the delayed response.
> 
> I just run (Python 3.7.9, Java openjdk 11.0.9.1) the script with the change I mentioned and it worked apparently well:
> 
> `python evaluate_from_file.py --references data/dev.pe.txt --hypotheses data/dev.mt.txt --step-size 1 --metrics ter`
> 
> Returns:
> 
> ```
> 1 	Score:  {'TER': 0.6521739130434783}
> 2 	Score:  {'TER': 0.5142857142857142}
> 3 	Score:  {'TER': 0.6}
> 4 	Score:  {'TER': 0.625}
> 5 	Score:  {'TER': 0.7692307692307693}
> 6 	Score:  {'TER': 0.7333333333333333}
> 7 	Score:  {'TER': 0.5555555555555556}
> 8 	Score:  {'TER': 0.875}
> 9 	Score:  {'TER': 0.6}
> 10 	Score:  {'TER': 0.8333333333333334}
> 11 	Score:  {'TER': 0.45454545454545453}
> 12 	Score:  {'TER': 0.25}
> 13 	Score:  {'TER': 0.9230769230769231}
> 14 	Score:  {'TER': 0.5294117647058824}
> ```
> 
> That is consistent with the scores in `dev.hter.txt`.

when i run(python 3.6 openjdk 1.8.0_275)the script you given
But my score is different from yours ：(
I'm very confused.

**Comment by genbei** [comment]
> Hi,
> sorry for the delayed response.
> 
> I just run (Python 3.7.9, Java openjdk 11.0.9.1) the script with the change I mentioned and it worked apparently well:
> 
> `python evaluate_from_file.py --references data/dev.pe.txt --hypotheses data/dev.mt.txt --step-size 1 --metrics ter`
> 
> Returns:
> 
> ```
> 1 	Score:  {'TER': 0.6521739130434783}
> 2 	Score:  {'TER': 0.5142857142857142}
> 3 	Score:  {'TER': 0.6}
> 4 	Score:  {'TER': 0.625}
> 5 	Score:  {'TER': 0.7692307692307693}
> 6 	Score:  {'TER': 0.7333333333333333}
> 7 	Score:  {'TER': 0.5555555555555556}
> 8 	Score:  {'TER': 0.875}
> 9 	Score:  {'TER': 0.6}
> 10 	Score:  {'TER': 0.8333333333333334}
> 11 	Score:  {'TER': 0.45454545454545453}
> 12 	Score:  {'TER': 0.25}
> 13 	Score:  {'TER': 0.9230769230769231}
> 14 	Score:  {'TER': 0.5294117647058824}
> ```
> 
> That is consistent with the scores in `dev.hter.txt`.

Excuse me, did you just change this line of code, `indices = range(n - step_size, min(n, len(ref)))`，why the scores we calculated are different, or can you send me your evaluate_from_file.py file

**Comment by lvapeab** [comment]
Yes, I changed that line as indicated. I attach you the file (you should remove the `txt` extension). Other than that, make sure you are using a proper encoding. In my system I have:


```shell_script
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```
[evaluate_from_file.py.txt](https://github.com/lvapeab/ter/files/5734079/evaluate_from_file.py.txt)

**Comment by genbei** [comment]
> Yes, I changed that line as indicated. I attach you the file (you should remove the `txt` extension). Other than that, make sure you are using a proper encoding. In my system I have:
> 
> ```
> LC_ALL=en_US.UTF-8
> LANG=en_US.UTF-8
> ```
> 
> [evaluate_from_file.py.txt](https://github.com/lvapeab/ter/files/5734079/evaluate_from_file.py.txt)

> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Will this be affected？
